{% set name = "log4cplus" %}
{% set version = "2.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}-stable/{{ version }}/{{ name }}-{{ version }}.tar.gz
    fn: {{ name }}-{{ version }}.tar.gz
    sha256: 42dc435928917fd2f847046c4a0c6086b2af23664d198c7fc1b982c0bfe600c1
  - path: CMakeLists.txt

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [unix]
    - ninja  # [win]

test:
  commands:
    - test -f $PREFIX/include/log4cplus/appender.h  # [unix]
    - test -f $PREFIX/include/log4cplus/logger.h  # [unix]
    - test -f $PREFIX/lib/liblog4cplus.so  # [linux]
    - test -f $PREFIX/lib/liblog4cplus.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\bin\\log4cplusU.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\log4cplusU.lib exit 1  # [win]

about:
  home: https://sourceforge.net/projects/log4cplus/
  license: Apache-2.0
  license_file: LICENSE
  summary: A simple to use C++ logging API.
  description: |
    log4cplus is a simple to use C++17 logging API providing thread--safe,
    flexible, and arbitrarily granular control over log management and
    configuration. It is modeled after the Java log4j API.
  dev_url: https://github.com/log4cplus/log4cplus
  doc_url: https://sourceforge.net/projects/log4cplus/

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
